# Generated by Django 3.2.9 on 2021-12-01 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacc_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slots',
            name='person_nric',
        ),
        migrations.AddField(
            model_name='persons',
            name='person_last4nric',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slots',
            name='person_last4nric',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='vacc_app.persons'),
            preserve_default=False,
        ),
    ]
